FWDRAPUtils.onReady(function(){
    new FWDRAP({
        //main settings
        instanceName:"player1",
        parentId:"myDiv",
        playlistsId:"playlists",
        mainFolderPath:"content",
        skinPath:"modern_skin_white",
        showSoundCloudUserNameInTitle:"yes",
        googleAnalyticsTrackingCode:"",
        useDeepLinking:"yes",
        useYoutube:"yes",
        useVideo:"yes",
        rightClickContextMenu:"default",
        showButtonsToolTips:"yes",
        initializeOnlyWhenVisible:"no",
        addKeyboardSupport:"yes",
        autoPlay:"no",
        loop:"no",
        shuffle:"no",
        useHEXColorsForSkin:"no",
        privatePassword:"428c841430ea18a70f7b06525d4b748a",
        soundCloudAPIKey:"4e6c7139ca2791a89863367ba374a28e",
        normalHEXButtonsColor:"#FF0000",
        selectedHEXButtonsColor:"#00FF00",
        maxWidth:871,
        volume:.8,
        toolTipsButtonsHideDelay:1.5,
        toolTipsButtonFontColor:"#000000",
        //controller settings
        animateOnIntro:"yes",
        showFullScreenButton:"yes",
        showNextAndPrevButtons:"yes",
        showThumbnail:"yes",
        showSoundAnimation:"yes",
        showLoopButton:"yes",
        showShuffleButton:"yes",
        showDownloadMp3Button:"yes",
        showBuyButton:"yes",
        showShareButton:"yes",
        showMainScrubberAndVolumeScrubberToolTipLabel:"yes",
        disableAudioScrubbar:"no",
        expandBackground:"no",
        titleColor:"#000000",
        timeColor:"#6a6a6a",
        scrubbersToolTipLabelBackgroundColor:"#FFFFFF",
        scrubbersToolTipLabelFontColor:"#5a5a5a",
        //controller align and size settings (described in detail in the documentation!)
        controllerHeight:85,
        startSpaceBetweenButtons:10,
        spaceBetweenButtons:10,
        separatorOffsetOutSpace:4,
        separatorOffsetInSpace:7,
        lastButtonsOffsetTop:7,
        allButtonsOffsetTopAndBottom:15,
        titleBarOffsetTop:12,
        mainScrubberOffsetTop:53,
        spaceBetweenMainScrubberAndTime:6,
        startTimeSpace:10,
        scrubbersOffsetWidth:3,
        scrubbersOffestTotalWidth:-6,
        volumeButtonAndScrubberOffsetTop:46,
        spaceBetweenVolumeButtonAndScrubber:5,
        volumeScrubberOffestWidth:2,
        scrubberOffsetBottom:6,
        equlizerOffsetLeft:2,
        //playlists window settings
        showPlaylistsSearchInput:"yes",
        usePlaylistsSelectBox:"yes",
        showPlaylistsSelectBoxNumbers:"yes",
        showPlaylistsButtonAndPlaylists:"yes",
        showPlaylistsByDefault:"no",
        randomizePlaylist:"no",
        playlistLoop:"yes",
        thumbnailSelectedType:"opacity",
        startAtPlaylist:0,
        startAtTrack:0,
        startAtRandomTrack:"no",
        buttonsMargins:7,
        thumbnailMaxWidth:350,
        thumbnailMaxHeight:350,
        horizontalSpaceBetweenThumbnails:40,
        verticalSpaceBetweenThumbnails:40,
        mainSelectorBackgroundSelectedColor:"#000000",
        mainSelectorTextNormalColor:"#000000",
        mainSelectorTextSelectedColor:"#FFFFFF",
        mainButtonTextNormalColor:"#6a6a6a",
        mainButtonTextSelectedColor:"#000000",
        //playlist settings
        playTrackAfterPlaylistLoad:"no",
        showPlayListButtonAndPlaylist:"yes",
        showPlayListOnAndroid:"yes",
        showPlayListByDefault:"no",
        showPlaylistItemPlayButton:"yes",
        showPlaylistItemDownloadButton:"yes",
        showPlaylistItemBuyButton:"yes",
        forceDisableDownloadButtonForPodcast:"yes",
        forceDisableDownloadButtonForOfficialFM:"yes",
        forceDisableDownloadButtonForFolder:"yes",
        addScrollBarMouseWheelSupport:"yes",
        showTracksNumbers:"yes",
        playlistBackgroundColor:"#AAAAAA",
        trackTitleNormalColor:"#6a6a6a",
        trackTitleSelectedColor:"#000000",
        trackDurationColor:"#6a6a6a",
        maxPlaylistItems:100,
        nrOfVisiblePlaylistItems:12,
        trackTitleOffsetLeft:0,
        playPauseButtonOffsetLeftAndRight:11,
        durationOffsetRight:9,
        downloadButtonOffsetRight:11,
        scrollbarOffestWidth:7,
        //playback rate / speed
        showPlaybackRateButton:"yes",
        defaultPlaybackRate:1, //min - 0.5 / max - 3
        playbackRateWindowTextColor:"#FFFFFF",
        //login
        isLoggedIn:"yes",
        playTrackOnlyWhenLoggedIn:"yes",
        loggedInMessage:"Please login to play this track.",
        //password window
        borderColor:"#333333",
        secondaryLabelsColor:"#a1a1a1",
        textColor:"#5a5a5a",
        inputBackgroundColor:"#000000",
        inputColor:"#FFFFFF",
        //search bar settings
        showSearchBar:"yes",
        showSortButtons:"yes",
        searchInputColor:"#000000",
        searchBarHeight:42,
        inputSearchTextOffsetTop:2,
        inputSearchOffsetLeft:0,
        //popup settings
        showPopupButton:"yes",
        popupWindowBackgroundColor:"#6a6a6a",
        popupWindowWidth:800,
        popupWindowHeight:460,
        //a to b loop
        atbTimeTextColorNormal:"#000000",
        atbTimeTextColorSelected:"#000000",
        atbButtonTextNormalColor:"#888888",
        atbButtonTextSelectedColor:"#FFFFFF",
        atbButtonBackgroundNormalColor:"#FFFFFF",
        atbButtonBackgroundSelectedColor:"#000000"
    });
})

function buyCustomFunction(){
    alert("The buy button can open a custom link or a custom javascript function.");
}